# Copyright (C) 2014 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/jsr/d10f/setup-makefiles.sh

# ADSP

PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/bin/adsprpcd:system/bin/adsprpcd
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libadsprpc.so:system/vendor/lib/libadsprpc.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libfastcvadsp_stub.so:system/vendor/lib/libfastcvadsp_stub.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libfastcvopt.so:system/vendor/lib/libfastcvopt.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libscve.so:system/vendor/lib/libscve.so

PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/rfsa/adsp/libadsp_denoise_skel.so:system/vendor/lib/rfsa/adsp/libadsp_denoise_skel.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/rfsa/adsp/libapps_mem_heap.so:system/vendor/lib/rfsa/adsp/libapps_mem_heap.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/rfsa/adsp/libdspCV_skel.so:system/vendor/lib/rfsa/adsp/libdspCV_skel.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/rfsa/adsp/libfastcvadsp.so:system/vendor/lib/rfsa/adsp/libfastcvadsp.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/rfsa/adsp/libfastcvadsp_skel.so:system/vendor/lib/rfsa/adsp/libfastcvadsp_skel.so

# Audio

PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/etc/acdbdata/MTP/MTP_Bluetooth_cal.acdb:system/etc/acdbdata/MTP/MTP_Bluetooth_cal.acdb
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/etc/acdbdata/MTP/MTP_General_cal.acdb:system/etc/acdbdata/MTP/MTP_General_cal.acdb
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/etc/acdbdata/MTP/MTP_Global_cal.acdb:system/etc/acdbdata/MTP/MTP_Global_cal.acdb
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/etc/acdbdata/MTP/MTP_Handset_cal.acdb:system/etc/acdbdata/MTP/MTP_Handset_cal.acdb
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/etc/acdbdata/MTP/MTP_Hdmi_cal.acdb:system/etc/acdbdata/MTP/MTP_Hdmi_cal.acdb
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/etc/acdbdata/MTP/MTP_Headset_cal.acdb:system/etc/acdbdata/MTP/MTP_Headset_cal.acdb
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/etc/acdbdata/MTP/MTP_Speaker_cal.acdb:system/etc/acdbdata/MTP/MTP_Speaker_cal.acdb 

PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libacdbloader.so:system/vendor/lib/libacdbloader.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libacdbrtac.so:system/vendor/lib/libacdbrtac.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libadiertac.so:system/vendor/lib/libadiertac.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libaudcal.so:system/vendor/lib/libaudcal.so

PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/soundfx/libqcbassboost.so:system/vendor/lib/soundfx/libqcbassboost.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/soundfx/libqcreverb.so:system/vendor/lib/soundfx/libqcreverb.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/soundfx/libqcvirt.so:system/vendor/lib/soundfx/libqcvirt.so

PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/etc/audio_effects.conf:system/vendor/etc/audio_effects.conf

# Bluetooth

PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/bin/btnvtool:system/bin/btnvtool
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/bin/hci_qcomm_init:system/bin/hci_qcomm_init
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libbtnv.so:system/vendor/lib/libbtnv.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libbt-vendor.so:system/vendor/lib/libbt-vendor.so

# Camera

#PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/bin/mm-qcamera-daemon:system/bin/mm-qcamera-daemon
#PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/bin/mm-qcamera-app:system/bin/mm-qcamera-app
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/lib/libmmcamera_interface.so:system/lib/libmmcamera_interface.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/lib/libmmjpeg_interface.so:system/lib/libmmjpeg_interface.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/lib/libmm-qcamera.so:system/lib/libmm-qcamera.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/lib/libqomx_core.so:system/lib/libqomx_core.so


PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libchromatix_imx135_common.so:system/vendor/lib/libchromatix_imx135_common.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libchromatix_imx135_default_video.so:system/vendor/lib/libchromatix_imx135_default_video.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libchromatix_imx135_hfr_120.so:system/vendor/lib/libchromatix_imx135_hfr_120.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libchromatix_imx135_preview.so:system/vendor/lib/libchromatix_imx135_preview.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libchromatix_imx135_snapshot.so:system/vendor/lib/libchromatix_imx135_snapshot.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libchromatix_imx135_video_hd.so:system/vendor/lib/libchromatix_imx135_video_hd.so


PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libchromatix_ov2720_common.so:system/vendor/lib/libchromatix_ov2720_common.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libchromatix_ov2720_default_video.so:system/vendor/lib/libchromatix_ov2720_default_video.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libchromatix_ov2720_hfr.so:system/vendor/lib/libchromatix_ov2720_hfr.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libchromatix_ov2720_liveshot.so:system/vendor/lib/libchromatix_ov2720_liveshot.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libchromatix_ov2720_preview.so:system/vendor/lib/libchromatix_ov2720_preview.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libchromatix_ov2720_zsl.so:system/vendor/lib/libchromatix_ov2720_zsl.so


PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libchromatix_ov5648_oty5f03_common.so:system/vendor/lib/libchromatix_ov5648_oty5f03_common.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libchromatix_ov5648_oty5f03_default_video.so:system/vendor/lib/libchromatix_ov5648_oty5f03_default_video.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libchromatix_ov5648_oty5f03_preview.so:system/vendor/lib/libchromatix_ov5648_oty5f03_preview.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libchromatix_ov5648_oty5f03_snapshot.so:system/vendor/lib/libchromatix_ov5648_oty5f03_snapshot.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libchromatix_ov5648_oty5f03_zsl.so:system/vendor/lib/libchromatix_ov5648_oty5f03_zsl.so
    

PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libchromatix_ov8825_common.so:system/vendor/lib/libchromatix_ov8825_common.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libchromatix_ov8825_default_video.so:system/vendor/lib/libchromatix_ov8825_default_video.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libchromatix_ov8825_hfr_60fps.so:system/vendor/lib/libchromatix_ov8825_hfr_60fps.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libchromatix_ov8825_hfr_90fps.so:system/vendor/lib/libchromatix_ov8825_hfr_90fps.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libchromatix_ov8825_hfr_120fps.so:system/vendor/lib/libchromatix_ov8825_hfr_120fps.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libchromatix_ov8825_liveshot.so:system/vendor/lib/libchromatix_ov8825_liveshot.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libchromatix_ov8825_liveshot_hd.so:system/vendor/lib/libchromatix_ov8825_liveshot_hd.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libchromatix_ov8825_preview.so:system/vendor/lib/libchromatix_ov8825_preview.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libchromatix_ov8825_preview_hd.so:system/vendor/lib/libchromatix_ov8825_preview_hd.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libchromatix_ov8825_snapshot.so:system/vendor/lib/libchromatix_ov8825_snapshot.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libchromatix_ov8825_snapshot_hd.so:system/vendor/lib/libchromatix_ov8825_snapshot_hd.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libchromatix_ov8825_video_hd.so:system/vendor/lib/libchromatix_ov8825_video_hd.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libchromatix_ov8825_zsl.so:system/vendor/lib/libchromatix_ov8825_zsl.so
    

PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libchromatix_ov8865_q8v18a_common.so:system/vendor/lib/libchromatix_ov8865_q8v18a_common.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libchromatix_ov8865_q8v18a_default_video.so:system/vendor/lib/libchromatix_ov8865_q8v18a_default_video.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libchromatix_ov8865_q8v18a_hfr_60fps.so:system/vendor/lib/libchromatix_ov8865_q8v18a_hfr_60fps.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libchromatix_ov8865_q8v18a_hfr_90fps.so:system/vendor/lib/libchromatix_ov8865_q8v18a_hfr_90fps.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libchromatix_ov8865_q8v18a_hfr_120fps.so:system/vendor/lib/libchromatix_ov8865_q8v18a_hfr_120fps.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libchromatix_ov8865_q8v18a_liveshot.so:system/vendor/lib/libchromatix_ov8865_q8v18a_liveshot.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libchromatix_ov8865_q8v18a_preview.so:system/vendor/lib/libchromatix_ov8865_q8v18a_preview.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libchromatix_ov8865_q8v18a_snapshot.so:system/vendor/lib/libchromatix_ov8865_q8v18a_snapshot.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libchromatix_ov8865_q8v18a_video_hd.so:system/vendor/lib/libchromatix_ov8865_q8v18a_video_hd.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libchromatix_ov8865_q8v18a_zsl.so:system/vendor/lib/libchromatix_ov8865_q8v18a_zsl.so


PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libchromatix_ov9724_common.so:system/vendor/lib/libchromatix_ov9724_common.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libchromatix_ov9724_default_video.so:system/vendor/lib/libchromatix_ov9724_default_video.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libchromatix_ov9724_liveshot.so:system/vendor/lib/libchromatix_ov9724_liveshot.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libchromatix_ov9724_preview.so:system/vendor/lib/libchromatix_ov9724_preview.so


PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libchromatix_ov9760_q1v05a_common.so:system/vendor/lib/libchromatix_ov9760_q1v05a_common.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libchromatix_ov9760_q1v05a_default_video.so:system/vendor/lib/libchromatix_ov9760_q1v05a_default_video.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libchromatix_ov9760_q1v05a_liveshot.so:system/vendor/lib/libchromatix_ov9760_q1v05a_liveshot.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libchromatix_ov9760_q1v05a_preview.so:system/vendor/lib/libchromatix_ov9760_q1v05a_preview.so


PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libchromatix_ov13850_common.so:system/vendor/lib/libchromatix_ov13850_common.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libchromatix_ov13850_default_video.so:system/vendor/lib/libchromatix_ov13850_default_video.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libchromatix_ov13850_hfr_60fps.so:system/vendor/lib/libchromatix_ov13850_hfr_60fps.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libchromatix_ov13850_hfr_90fps.so:system/vendor/lib/libchromatix_ov13850_hfr_90fps.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libchromatix_ov13850_hfr_120fps.so:system/vendor/lib/libchromatix_ov13850_hfr_120fps.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libchromatix_ov13850_liveshot.so:system/vendor/lib/libchromatix_ov13850_liveshot.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libchromatix_ov13850_preview.so:system/vendor/lib/libchromatix_ov13850_preview.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libchromatix_ov13850_snapshot.so:system/vendor/lib/libchromatix_ov13850_snapshot.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libchromatix_ov13850_video_hd.so:system/vendor/lib/libchromatix_ov13850_video_hd.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libchromatix_ov13850_zsl.so:system/vendor/lib/libchromatix_ov13850_zsl.so


PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libchromatix_t4k37ab_common.so:system/vendor/lib/libchromatix_t4k37ab_common.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libchromatix_t4k37ab_default_video.so:system/vendor/lib/libchromatix_t4k37ab_default_video.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libchromatix_t4k37ab_preview.so:system/vendor/lib/libchromatix_t4k37ab_preview.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libchromatix_t4k37ab_snapshot.so:system/vendor/lib/libchromatix_t4k37ab_snapshot.so
    

PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libjpegdhw.so:system/vendor/lib/libjpegdhw.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libjpegehw.so:system/vendor/lib/libjpegehw.so


PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libmmcamera_f4k37ab_qtech_t4k37_eeprom.so:system/vendor/lib/libmmcamera_f4k37ab_qtech_t4k37_eeprom.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libmmcamera_faceproc.so:system/vendor/lib/libmmcamera_faceproc.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libmmcamera_hdr_gb_lib.so:system/vendor/lib/libmmcamera_hdr_gb_lib.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libmmcamera_hdr_lib.so:system/vendor/lib/libmmcamera_hdr_lib.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libmmcamera_hi256.so:system/vendor/lib/libmmcamera_hi256.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libmmcamera_imglib.so:system/vendor/lib/libmmcamera_imglib.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libmmcamera_ov2720.so:system/vendor/lib/libmmcamera_ov2720.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libmmcamera_ov5648_oty5f03.so:system/vendor/lib/libmmcamera_ov5648_oty5f03.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libmmcamera_ov8825.so:system/vendor/lib/libmmcamera_ov8825.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libmmcamera_ov8865_q8v18a.so:system/vendor/lib/libmmcamera_ov8865_q8v18a.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libmmcamera_ov9724.so:system/vendor/lib/libmmcamera_ov9724.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libmmcamera_ov9760_q1v05a.so:system/vendor/lib/libmmcamera_ov9760_q1v05a.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libmmcamera_ov13850.so:system/vendor/lib/libmmcamera_ov13850.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libmmcamera_t4k37ab.so:system/vendor/lib/libmmcamera_t4k37ab.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libmmcamera_tintless_algo.so:system/vendor/lib/libmmcamera_tintless_algo.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libmmcamera_tintless_bg_pca_algo.so:system/vendor/lib/libmmcamera_tintless_bg_pca_algo.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libmmcamera_tuning.so:system/vendor/lib/libmmcamera_tuning.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libmmcamera_wavelet_lib.so:system/vendor/lib/libmmcamera_wavelet_lib.so


PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libmmcamera2_c2d_module.so:system/vendor/lib/libmmcamera2_c2d_module.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libmmcamera2_cpp_module.so:system/vendor/lib/libmmcamera2_cpp_module.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libmmcamera2_iface_modules.so:system/vendor/lib/libmmcamera2_iface_modules.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libmmcamera2_imglib_modules.so:system/vendor/lib/libmmcamera2_imglib_modules.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libmmcamera2_isp_modules.so:system/vendor/lib/libmmcamera2_isp_modules.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libmmcamera2_pproc_modules.so:system/vendor/lib/libmmcamera2_pproc_modules.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libmmcamera2_sensor_modules.so:system/vendor/lib/libmmcamera2_sensor_modules.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libmmcamera2_stats_algorithm.so:system/vendor/lib/libmmcamera2_stats_algorithm.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libmmcamera2_stats_modules.so:system/vendor/lib/libmmcamera2_stats_modules.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libmmcamera2_vpe_module.so:system/vendor/lib/libmmcamera2_vpe_module.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libmmcamera2_wnr_module.so:system/vendor/lib/libmmcamera2_wnr_module.so


PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libmmipl.so:system/vendor/lib/libmmipl.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libmmjpeg.so:system/vendor/lib/libmmjpeg.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libmmqjpeg_codec.so:system/vendor/lib/libmmqjpeg_codec.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/liboemcamera.so:system/vendor/lib/liboemcamera.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libqomx_jpegdec.so:system/vendor/lib/libqomx_jpegdec.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libqomx_jpegenc.so:system/vendor/lib/libqomx_jpegenc.so


# Camera firmware

PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/etc/firmware/cpp_firmware_v1_1_1.fw:system/etc/firmware/cpp_firmware_v1_1_1.fw
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/etc/firmware/cpp_firmware_v1_1_6.fw:system/etc/firmware/cpp_firmware_v1_1_6.fw
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/etc/firmware/cpp_firmware_v1_2_0.fw:system/etc/firmware/cpp_firmware_v1_2_0.fw

# Color convertor

PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libI420colorconvert.so:system/vendor/lib/libI420colorconvert.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libmm-color-convertor.so:system/vendor/lib/libmm-color-convertor.so

# DRM

PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/bin/qseecomd:system/bin/qseecomd
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/lib/libWVphoneAPI.so:system/lib/libWVphoneAPI.so
#PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/bin/qseecom_sample_client:system/bin/qseecom_sample_client
#PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/bin/qseecom_security_test:system/bin/qseecom_security_test
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/drm/libdrmprplugin.so:system/vendor/lib/drm/libdrmprplugin.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/drm/libdrmwvmplugin.so:system/vendor/lib/drm/libdrmwvmplugin.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libdrmdecrypt.so:system/vendor/lib/libdrmdecrypt.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libdrmdiag.so:system/vendor/lib/libdrmdiag.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libdrmfs.so:system/vendor/lib/libdrmfs.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libdrmtime.so:system/vendor/lib/libdrmtime.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libQSEEComAPI.so:system/vendor/lib/libQSEEComAPI.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/librpmb.so:system/vendor/lib/librpmb.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libssd.so:system/vendor/lib/libssd.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libStDrvInt.so:system/vendor/lib/libStDrvInt.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libwvdrm_L3.so:system/vendor/lib/libwvdrm_L3.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libwvm.so:system/vendor/lib/libwvm.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libWVStreamControlAPI_L3.so:system/vendor/lib/libWVStreamControlAPI_L3.so 

# Fastcharge

#PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/bin/hvdcp:system/bin/hvdcp

# FM radio and GPS

PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/bin/fmconfig:system/bin/fmconfig
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/bin/fm_qsoc_patches:system/bin/fm_qsoc_patches
#PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/bin/location-mq:system/bin/location-mq
#PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/bin/xtwifi-client:system/bin/xtwifi-client
#PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/bin/xtwifi-inet-agent:system/bin/xtwifi-inet-agent
#PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/bin/lowi-server:system/bin/lowi-server
#PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/etc/permissions/com.qualcomm.location.xml:system/etc/permissions/com.qualcomm.location.xml
#PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/etc/gps.conf:system/etc/gps.conf
#PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/etc/izat.conf:system/etc/izat.conf
#PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/etc/lowi.conf:system/etc/lowi.conf
#PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/etc/quipc.conf:system/etc/quipc.conf
#PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/etc/msap.conf:system/etc/msap.conf
#PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/etc/sap.conf:system/etc/sap.conf
#PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/etc/xtwifi.conf:system/etc/xtwifi.conf
#PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/etc/cacert_location.pem:system/etc/cacert_location.pem
#PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/etc/xtra_root_cert.pem:system/etc/xtra_root_cert.pem
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/lib/libloc_api_v02.so:system/lib/libloc_api_v02.so
#PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/lib/libloc_ds_api.so:system/lib/libloc_ds_api.so
#PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/lib/libloc_xtra.so:system/lib/libloc_xtra.so
#PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/lib/liblocSDK3.so:system/lib/liblocSDK3.so
#PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libalarmservice_jni.so:system/vendor/lib/libalarmservice_jni.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libgeofence.so:system/vendor/lib/libgeofence.so
#PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libizat_core.so:system/vendor/lib/libizat_core.so
#PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/liblbs_core.so:system/vendor/lib/liblbs_core.so
#PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/liblocationservice.so:system/vendor/lib/liblocationservice.so
#PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libloc_ext.so:system/vendor/lib/libloc_ext.so
#PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/liblowi_client.so:system/vendor/lib/liblowi_client.so
#PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libquipc_os_api.so:system/vendor/lib/libquipc_os_api.so
#PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libquipc_ulp_adapter.so:system/vendor/lib/libquipc_ulp_adapter.so
#PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libulp2.so:system/vendor/lib/libulp2.so
#PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libxtadapter.so:system/vendor/lib/libxtadapter.so
#PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libxtwifi_ulp_adaptor.so:system/vendor/lib/libxtwifi_ulp_adaptor.so
#PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libxtwifi_zpp_adaptor.so:system/vendor/lib/libxtwifi_zpp_adaptor.so
#PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libxt_native.so:system/vendor/lib/libxt_native.so

# Graphics

PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/etc/firmware/a225_pfp.fw:system/etc/firmware/a225_pfp.fw
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/etc/firmware/a225_pm4.fw:system/etc/firmware/a225_pm4.fw
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/etc/firmware/a225p5_pm4.fw:system/etc/firmware/a225p5_pm4.fw
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/etc/firmware/a300_pfp.fw:system/etc/firmware/a300_pfp.fw
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/etc/firmware/a300_pm4.fw:system/etc/firmware/a300_pm4.fw
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/etc/firmware/a330_pfp.fw:system/etc/firmware/a330_pfp.fw
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/etc/firmware/a330_pm4.fw:system/etc/firmware/a330_pm4.fw
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/etc/firmware/leia_pfp_470.fw:system/etc/firmware/leia_pfp_470.fw
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/etc/firmware/leia_pm4_470.fw:system/etc/firmware/leia_pm4_470.fw
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/egl/eglsubAndroid.so:system/vendor/lib/egl/eglsubAndroid.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/egl/libEGL_adreno.so:system/vendor/lib/egl/libEGL_adreno.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/egl/libGLESv1_CM_adreno.so:system/vendor/lib/egl/libGLESv1_CM_adreno.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/egl/libGLESv2_adreno.so:system/vendor/lib/egl/libGLESv2_adreno.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/egl/libq3dtools_adreno.so:system/vendor/lib/egl/libq3dtools_adreno.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libadreno_utils.so:system/vendor/lib/libadreno_utils.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libC2D2.so:system/vendor/lib/libC2D2.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libc2d30.so:system/vendor/lib/libc2d30.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libc2d30-a3xx.so:system/vendor/lib/libc2d30-a3xx.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libCB.so:system/vendor/lib/libCB.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libgsl.so:system/vendor/lib/libgsl.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libllvm-a3xx.so:system/vendor/lib/libllvm-a3xx.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libllvm-qcom.so:system/vendor/lib/libllvm-qcom.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libOpenCL.so:system/vendor/lib/libOpenCL.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libOpenVG.so:system/vendor/lib/libOpenVG.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/librs_adreno.so:system/vendor/lib/librs_adreno.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/librs_adreno_sha1.so:system/vendor/lib/librs_adreno_sha1.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libRSDriver_adreno.so:system/vendor/lib/libRSDriver_adreno.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libsc-a3xx.so:system/vendor/lib/libsc-a3xx.so

# Keystore

PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/firmware/keymaster/keymaster.b00:system/vendor/firmware/keymaster/keymaster.b00
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/firmware/keymaster/keymaster.b01:system/vendor/firmware/keymaster/keymaster.b01
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/firmware/keymaster/keymaster.b02:system/vendor/firmware/keymaster/keymaster.b02
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/firmware/keymaster/keymaster.b03:system/vendor/firmware/keymaster/keymaster.b03
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/firmware/keymaster/keymaster.mdt:system/vendor/firmware/keymaster/keymaster.mdt

# Media

#PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/bin/imsdatadaemon:system/bin/imsdatadaemon
#PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/bin/imsqmidaemon:system/bin/imsqmidaemon
#PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/bin/ims_rtp_daemon:system/bin/ims_rtp_daemon
#PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/etc/permissions/ims.xml:system/etc/permissions/ims.xml
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/lib-dplmedia.so:system/vendor/lib/lib-dplmedia.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/lib-imsdpl.so:system/vendor/lib/lib-imsdpl.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/lib-imsqimf.so:system/vendor/lib/lib-imsqimf.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/lib-imsrcs.so:system/vendor/lib/lib-imsrcs.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/lib-imss.so:system/vendor/lib/lib-imss.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/lib-imsSDP.so:system/vendor/lib/lib-imsSDP.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/lib-imsvt.so:system/vendor/lib/lib-imsvt.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/lib-imsxml.so:system/vendor/lib/lib-imsxml.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libmmrtpencoder.so:system/vendor/lib/libmmrtpencoder.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libmmrtpdecoder.so:system/vendor/lib/libmmrtpdecoder.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/liblistenhardware.so:system/vendor/lib/liblistenhardware.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/liblistenjni.so:system/vendor/lib/liblistenjni.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/liblistensoundmodel.so:system/vendor/lib/liblistensoundmodel.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/liblisten.so:system/vendor/lib/liblisten.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libDivxDrm.so:system/vendor/lib/libDivxDrm.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libExtendedExtractor.so:system/vendor/lib/libExtendedExtractor.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libFileMux.so:system/vendor/lib/libFileMux.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libmmosal.so:system/vendor/lib/libmmosal.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libmmparser.so:system/vendor/lib/libmmparser.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libOmxAacDec.so:system/vendor/lib/libOmxAacDec.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libOmxAmrwbplusDec.so:system/vendor/lib/libOmxAmrwbplusDec.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libOmxEvrcDec.so:system/vendor/lib/libOmxEvrcDec.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libOmxMux.so:system/vendor/lib/libOmxMux.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libOmxQcelp13Dec.so:system/vendor/lib/libOmxQcelp13Dec.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libOmxWmaDec.so:system/vendor/lib/libOmxWmaDec.so

# Perf

PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/bin/mpdecision:system/bin/mpdecision
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libqc-opt.so:system/vendor/lib/libqc-opt.so

# Postprocessing

PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/bin/mm-pp-daemon:system/bin/mm-pp-daemon
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libdisp-aba.so:system/vendor/lib/libdisp-aba.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libmm-abl.so:system/vendor/lib/libmm-abl.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libmm-abl-oem.so:system/vendor/lib/libmm-abl-oem.so

# Qualcomm

#PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/bin/qcom-system-daemon:system/bin/qcom-system-daemon
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/bin/irsc_util:system/bin/irsc_util
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libdiag.so:system/vendor/lib/libdiag.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libdsi_netctrl.so:system/vendor/lib/libdsi_netctrl.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libdsnetutils.so:system/vendor/lib/libdsnetutils.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libdsutils.so:system/vendor/lib/libdsutils.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libidl.so:system/vendor/lib/libidl.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libqcci_legacy.so:system/vendor/lib/libqcci_legacy.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libqdi.so:system/vendor/lib/libqdi.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libqdp.so:system/vendor/lib/libqdp.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libqmi.so:system/vendor/lib/libqmi.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libqmi_cci.so:system/vendor/lib/libqmi_cci.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libqmi_client_qmux.so:system/vendor/lib/libqmi_client_qmux.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libqmi_csi.so:system/vendor/lib/libqmi_csi.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libqmiservices.so:system/vendor/lib/libqmiservices.so

# Radio

PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/bin/netmgrd:system/bin/netmgrd
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/bin/qmuxd:system/bin/qmuxd
#PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/bin/rfs_access:system/bin/rfs_access
#PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/bin/rild:system/bin/rild
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/bin/rmt_storage:system/bin/rmt_storage
#PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/etc/permissions/qcnvitems.xml:system/etc/permissions/qcnvitems.xml
#PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/etc/permissions/qcrilhook.xml:system/etc/permissions/qcrilhook.xml
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/lib/libril.so:system/lib/libril.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libnetmgr.so:system/vendor/lib/libnetmgr.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libril-qc-qmi-1.so:system/vendor/lib/libril-qc-qmi-1.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libril-qcril-hook-oem.so:system/vendor/lib/libril-qcril-hook-oem.so

# Sensors

PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/bin/sensors.qcom:system/bin/sensors.qcom
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/hw/sensors.msm8226.so:system/vendor/lib/hw/sensors.msm8226.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libAKM8963.so:system/vendor/lib/libAKM8963.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libsensor1.so:system/vendor/lib/libsensor1.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libsensor_reg.so:system/vendor/lib/libsensor_reg.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libsensor_test.so:system/vendor/lib/libsensor_test.so
#PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libsensor_thresh.so:system/vendor/lib/libsensor_thresh.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libsensor_user_cal.so:system/vendor/lib/libsensor_user_cal.so

# Thermal

PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/bin/thermal-engine:system/bin/thermal-engine
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libthermalclient.so:system/vendor/lib/libthermalclient.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libthermalioctl.so:system/vendor/lib/libthermalioctl.so

# Time services

PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/bin/time_daemon:system/bin/time_daemon
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libtime_genoff.so:system/vendor/lib/libtime_genoff.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libtime_genoff.so:system/lib/libtime_genoff.so
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libTimeService.so:system/vendor/lib/libTimeService.so

# Venus (media) firmware

PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/etc/firmware/venus.b00:system/etc/firmware/venus.b00
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/etc/firmware/venus.b01:system/etc/firmware/venus.b01
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/etc/firmware/venus.b02:system/etc/firmware/venus.b02
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/etc/firmware/venus.b03:system/etc/firmware/venus.b03
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/etc/firmware/venus.b04:system/etc/firmware/venus.b04
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/etc/firmware/venus.mbn:system/etc/firmware/venus.mbn
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/etc/firmware/venus.mdt:system/etc/firmware/venus.mdt

# Wifi

PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/bin/ptt_socket_app:system/bin/ptt_socket_app

PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/etc/firmware/wcnss.b00:system/etc/firmware/wcnss.b00
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/etc/firmware/wcnss.b01:system/etc/firmware/wcnss.b01
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/etc/firmware/wcnss.b02:system/etc/firmware/wcnss.b02
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/etc/firmware/wcnss.b04:system/etc/firmware/wcnss.b04
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/etc/firmware/wcnss.b06:system/etc/firmware/wcnss.b06
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/etc/firmware/wcnss.b07:system/etc/firmware/wcnss.b07
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/etc/firmware/wcnss.b08:system/etc/firmware/wcnss.b08
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/etc/firmware/wcnss.b09:system/etc/firmware/wcnss.b09
PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/etc/firmware/wcnss.mdt:system/etc/firmware/wcnss.mdt

PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/lib/libqminvapi.so:system/lib/libqminvapi.so

# MMI

#PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/bin/mmi:system/bin/mmi
#PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/etc/mmi.cfg:system/etc/mmi.cfg
#PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libmmi.so:system/vendor/lib/libmmi.so
#PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libmmiipstreammmihttp.so:system/vendor/lib/libmmiipstreammmihttp.so
#PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libmmipl.so:system/vendor/lib/libmmipl.so
#PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libmmipstreamaal.so:system/vendor/lib/libmmipstreamaal.so
#PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libmmipstreamnetwork.so:system/vendor/lib/libmmipstreamnetwork.so
#PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libmmipstreamsourcehttp.so:system/vendor/lib/libmmipstreamsourcehttp.so
#PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/libmmipstreamutils.so:system/vendor/lib/libmmipstreamutils.so
#PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/mmi_audio.so:system/vendor/lib/mmi_audio.so
#PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/mmi_battery.so:system/vendor/lib/mmi_battery.so
#PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/mmi_bt.so:system/vendor/lib/mmi_bt.so
#PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/mmi_camera.so:system/vendor/lib/mmi_camera.so
#PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/mmi_flashlight.so:system/vendor/lib/mmi_flashlight.so
#PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/mmi_fm.so:system/vendor/lib/mmi_fm.so
#PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/mmi_gps_garden.so:system/vendor/lib/mmi_gps_garden.so
#PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/mmi_gsensor.so:system/vendor/lib/mmi_gsensor.so
#PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/mmi_gyroscope.so:system/vendor/lib/mmi_gyroscope.so
#PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/mmi_keypadbacklight.so:system/vendor/lib/mmi_keypadbacklight.so
#PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/mmi_lcd.so:system/vendor/lib/mmi_lcd.so
#PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/mmi_led.so:system/vendor/lib/mmi_led.so
#PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/mmi_lsensor.so:system/vendor/lib/mmi_lsensor.so
#PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/mmi_msensor.so:system/vendor/lib/mmi_msensor.so
#PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/mmi_psensor.so:system/vendor/lib/mmi_psensor.so
#PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/mmi_sdcard.so:system/vendor/lib/mmi_sdcard.so
#PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/mmi_sim.so:system/vendor/lib/mmi_sim.so
#PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/mmi_touch.so:system/vendor/lib/mmi_touch.so
#PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/mmi_touchpanel.so:system/vendor/lib/mmi_touchpanel.so
#PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/mmi_vibrator.so:system/vendor/lib/mmi_vibrator.so
#PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/mmi_volume.so:system/vendor/lib/mmi_volume.so
#PRODUCT_COPY_FILES += vendor/jsr/d10f/proprietary/vendor/lib/mmi_wifi.so:system/vendor/lib/mmi_wifi.so

