# Copyright (C) 2014 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/jsr/d10f/setup-makefiles.sh

$(call inherit-product, vendor/qcom/proprietary/common/config/device-vendor-d10f.mk)
$(call inherit-product, vendor/qcom/proprietary/common/config/device-vendor.mk)
$(call inherit-product, vendor/qcom/prebuilt-msm8226/target/prebuilt.mk)
$(call inherit-product, vendor/jsr/d10f/d10f-vendor-blobs.mk)
